### ISSUE TITLE
Add on_hover and on_click styles to delete button of task.

### ISSUE THREAD

**Issue by sahilpatil1804** [pshreyash11/SE-Lab-Practicle-8-Git-learning-#1]
The delete button has on hover and on click styling of default button class but we need to change it such that on hover, on click the delete button should have different shade of red.

**Comment by pshreyash11** [comment]
yes you are absolutely right !

**Comment by pshreyash11** [comment]
> The delete button has on hover and on click styling of default button class but we need to change it such that on hover, on click the delete button should have different shade of red.

yes you are absolutely right !
